### ISSUE TITLE
Exception when precompiling assets after an upgrade from 1.9.9 to 2.0.18

### ISSUE THREAD

**Issue by benorama** [bertramdev/grails-asset-pipeline#186]
We have upgraded asset-pipeline to 2.x on our all projects.
It worked flawlessly except for one pretty large angularJS-based project.

When running asset-precompile (Grails 2.4.4 / java version "1.8.0_25"), it throws the following exception:

``` java
java.lang.NoSuchMethodError: com.google.common.collect.Maps.immutableEnumMap(Ljava/util/Map;)Lcom/google/common/collect/ImmutableMap;
    at com.google.javascript.jscomp.parsing.parser.Keywords.<clinit>(Keywords.java:94)
    at com.google.javascript.jscomp.parsing.parser.Parser.peekId(Parser.java:2566)
    at com.google.javascript.jscomp.parsing.parser.Parser.peekId(Parser.java:2561)
    at com.google.javascript.jscomp.parsing.parser.Parser.peekLabelledStatement(Parser.java:1195)
    at com.google.javascript.jscomp.parsing.parser.Parser.parseStatementStandard(Parser.java:727)
    at com.google.javascript.jscomp.parsing.parser.Parser.parseSourceElement(Parser.java:506)
    at com.google.javascript.jscomp.parsing.parser.Parser.parseScriptElement(Parser.java:181)
    at com.google.javascript.jscomp.parsing.parser.Parser.parseGlobalSourceElements(Parser.java:163)
    at com.google.javascript.jscomp.parsing.parser.Parser.parseProgram(Parser.java:148)
    at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:102)
    at com.google.javascript.jscomp.JsAst.parse(JsAst.java:84)
    at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:50)
    at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:118)
    at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:1467)
    at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1369)
    at com.google.javascript.jscomp.Compiler.parse(Compiler.java:788)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:743)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:93)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:655)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:652)
    at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:699)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I tried to copy/paste the js file generating this exception in a small project and asset-precompile works successfully.

Do you have any idea on this issue?

Thanks.

**Comment by neoecos** [comment]
@benorama could you post a code snippet on how to exclude guava?

I'm having the same issue, and it's really annoying. Thank you!

**Comment by benorama** [comment]
Sure! 

```groovy
dependencies {
    ...
    compile('com.google.gdata:core:1.47.1') {
            exclude 'com.google.guava:guava' // Workaround to solve lib clash with Asset-pipeline plugin (java.lang.NoSuchMethodError: com.google.common.collect.Maps.immutableEnumMap during asset-precompile)
    }
    ...
}
```

**Comment by davydotcom** [comment]
This is a result of the closure minified requires guava

**Comment by neoecos** [comment]
Thank you @benorama, @davydotcom 

My problem was, I manually added the asset-pipeline (maven dependency, not plugin) and the guava dependency was not added to the project.

I added compile 'com.google.guava:guava:17.0' and it worked, so I added the asset-pipepeline plugin and started worked again.

**Comment by davydotcom** [comment]
Well thats odd are you using aether or ivy. Aether seems to have issues resolving transitive dependencies its kinda annoying. asset-pipeline-core depends on closure compiler which in turn loads up guava
